dist: trusty
sudo: true
language: c
env:
    PACKAGE_VERSION=`grep PKG_VERSION Makefile | sed 's/.*:=//'`
    PACKAGE_RELEASE=`grep PKG_RELEASE Makefile | sed 's/.*:=//'`
    PACKAGE_ARCH=`grep PKGARCH Makefile | sed 's/.*:=//'`

before_script:
    - wget https://downloads.openwrt.org/releases/18.06.1/targets/bcm53xx/generic/openwrt-sdk-18.06.1-bcm53xx_gcc-7.3.0_musl_eabi.Linux-x86_64.tar.xz
    - tar xf openwrt-sdk-18.06.1-bcm53xx_gcc-7.3.0_musl_eabi.Linux-x86_64.tar.xz
    - mkdir -p openwrt-sdk-18.06.1-bcm53xx_gcc-7.3.0_musl_eabi.Linux-x86_64/package/luci-app-speederv2
    - mv files tools Makefile openwrt-sdk-18.06.1-bcm53xx_gcc-7.3.0_musl_eabi.Linux-x86_64/package/luci-app-speederv2/
    - cd openwrt-sdk-18.06.1-bcm53xx_gcc-7.3.0_musl_eabi.Linux-x86_64
    - pushd package/luci-app-speederv2/tools/po2lmo
    - make
    - sudo make install
    - popd
    - make defconfig

script:
    - make package/luci-app-speederv2/compile V=s
    - stat bin/packages/arm_cortex-a9/base/luci-app-speederv2_${PACKAGE_VERSION}-${PACKAGE_RELEASE}_${PACKAGE_ARCH}.ipk
